import type { Metadata } from "next";
import {Raleway} from "next/font/google"
import "./globals.css";
import { Header } from "@/components";
import { QueryProvider } from "@/libs";

const raleway = Raleway({
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "UTSCHOOL",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${raleway.className} antialiased`}
      >
        <Header/>
        <QueryProvider>
          <main className="bg-gray-200 min-h-screen">
            {children}
          </main>
        </QueryProvider>
      </body>
    </html>
  );
}
