import type { Metadata } from "next";
import {Raleway} from "next/font/google"
import "./globals.css";
import { Header } from "@/components";
import { QueryProvider } from "@/libs";
import {NextIntlClientProvider} from 'next-intl';
import {getLocale, getMessages} from 'next-intl/server';

const raleway = Raleway({
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "UTSCHOOL",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const locale = await getLocale();
 
  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body
        className={`${raleway.className} antialiased`}
      >
          <NextIntlClientProvider messages={messages}>
          <QueryProvider>
            <main className="bg-black/95 min-h-screen">
              {children}
            </main>
          </QueryProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
