import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components";
import {Poppins} from "next/font/google"
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.min.css';
import { NextQueryClientProvider } from "@/lib/queryClientProvider";
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';

export const metadata: Metadata = {
  title: "UT School",
  description: "Generated by create next app",
};

const poopins = Poppins({
  subsets: ['latin'],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen ${poopins.className}`}
      >
        <NextQueryClientProvider>
          <Navbar/>
          {children}
          <ReactQueryDevtools/>
        </NextQueryClientProvider>

        <ToastContainer autoClose={5000} stacked/>
      </body>
    </html>
  );
}
