import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components";
import {Poppins} from "next/font/google"

export const metadata: Metadata = {
  title: "UT School",
  description: "Generated by create next app",
};

const poopins = Poppins({
  subsets: ['latin'],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen ${poopins.className}`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
