name: CI/CD for Laravel in Monorepo

on:
  push:
    branches:
      - main  # Atur branch sesuai dengan branch yang Anda gunakan
  pull_request:
    branches:
      - main

jobs:
  laravel-ci-cd:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: apps/backend/  # Set to Laravel app directory in monorepo

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy Production Server
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: apps/backend/  # Adjust to your Laravel app directory

  deploy-staging:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: apps/backend/  # Set to Laravel app directory in monorepo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: FTP Deploy
      # You may pin to the exact commit or the version.
      # uses: SamKirkland/FTP-Deploy-Action@8a24039354ee91000cb948cb4a1dbdf1a1b94a3c
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          # ftp server
          server: ftp.kaitodecode.com
          # ftp username
          username: staging@api-admin.kaitodecode.com
          # ftp password
          password: Robotcanggih1*
          # Server port to connect to (read your web hosts docs)
          port: 21
          # protocol to deploy with - ftp, ftps, or ftps-legacy
          protocol: ftp

          # Local directory to upload
          local-dir: apps/backend/
          # An array of glob patterns, these files will not be included in the publish/delete process
          exclude: |
            */.git
            */.git/**
            */node_modules/*
            */vendor/*